CREATE TABLE IF NOT EXISTS settings (id boolean PRIMARY KEY DEFAULT true CHECK(id), profile jsonb NOT NULL DEFAULT '{}', autopilot boolean NOT NULL DEFAULT true, daily_limit integer NOT NULL DEFAULT 10 CHECK(daily_limit BETWEEN 1 AND 50), updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO settings(id) VALUES(true) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS opportunities (id uuid PRIMARY KEY, kind text NOT NULL CHECK(kind IN ('job','client')), title text NOT NULL, company text NOT NULL, country text NOT NULL, source text NOT NULL, url text NOT NULL DEFAULT '', description text NOT NULL, status text NOT NULL DEFAULT 'new', score integer, reasons jsonb NOT NULL DEFAULT '[]', sample boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(kind,company,title));
CREATE TABLE IF NOT EXISTS runs (id uuid PRIMARY KEY, opportunity_id uuid REFERENCES opportunities(id), kind text NOT NULL, status text NOT NULL DEFAULT 'queued', steps jsonb NOT NULL DEFAULT '[]', error text, attempts integer NOT NULL DEFAULT 0, lease_until timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS one_active_run ON runs(opportunity_id) WHERE status IN ('queued','running');
CREATE TABLE IF NOT EXISTS artifacts (id uuid PRIMARY KEY, opportunity_id uuid REFERENCES opportunities(id), kind text NOT NULL, title text NOT NULL, content text NOT NULL, profile_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS decisions (id uuid PRIMARY KEY, opportunity_id uuid REFERENCES opportunities(id), kind text NOT NULL, title text NOT NULL, detail text NOT NULL, status text NOT NULL DEFAULT 'open', answer text, created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS one_open_decision ON decisions(kind,opportunity_id) WHERE status='open';
CREATE TABLE IF NOT EXISTS events (id bigserial PRIMARY KEY, type text NOT NULL, message text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS feedback (id uuid PRIMARY KEY, opportunity_id uuid REFERENCES opportunities(id) NOT NULL, outcome text NOT NULL CHECK(outcome IN ('replied','interview','rejected','won','no_reply')), note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(opportunity_id));
CREATE TABLE IF NOT EXISTS worker_health (id boolean PRIMARY KEY DEFAULT true CHECK(id), heartbeat timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sources(id uuid PRIMARY KEY, provider text NOT NULL CHECK(provider IN ('greenhouse','lever')), slug text NOT NULL, company text NOT NULL, keywords text NOT NULL DEFAULT 'engineer,developer', enabled boolean NOT NULL DEFAULT true, last_sync timestamptz, sync_error text, UNIQUE(provider,slug));
CREATE TABLE IF NOT EXISTS integration_state(id boolean PRIMARY KEY DEFAULT true CHECK(id), user_id uuid NOT NULL, session_id text);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS ai_assist boolean NOT NULL DEFAULT false;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS input_tokens integer;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS output_tokens integer;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS input_snapshot jsonb;
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS cache_key text;
CREATE UNIQUE INDEX IF NOT EXISTS unique_artifact_cache ON artifacts(cache_key) WHERE cache_key IS NOT NULL;
ALTER TABLE integration_state ADD COLUMN IF NOT EXISTS auth_configs jsonb NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS artifact_revisions(id uuid PRIMARY KEY,artifact_id uuid NOT NULL REFERENCES artifacts(id),content text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE artifacts ADD COLUMN IF NOT EXISTS edited_at timestamptz;
ALTER TABLE settings DROP CONSTRAINT IF EXISTS settings_daily_limit_check;
ALTER TABLE settings ADD CONSTRAINT settings_daily_limit_check CHECK(daily_limit BETWEEN 1 AND 1000);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS execution_mode text NOT NULL DEFAULT 'balanced' CHECK(execution_mode IN ('balanced','performance'));
ALTER TABLE settings ADD COLUMN IF NOT EXISTS ai_daily_limit integer NOT NULL DEFAULT 2 CHECK(ai_daily_limit BETWEEN 0 AND 100);
ALTER TABLE runs ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE worker_health ADD COLUMN IF NOT EXISTS detail jsonb NOT NULL DEFAULT '{}';
CREATE INDEX IF NOT EXISTS ready_package_runs ON runs(next_attempt_at,created_at) WHERE status='queued' AND kind='package';
CREATE TABLE IF NOT EXISTS knowledge_facts(id text PRIMARY KEY,topic text NOT NULL,content text NOT NULL,source text NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS handled_by text;
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS resolution jsonb;
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS resolution_version text;
CREATE TABLE IF NOT EXISTS audit_log(id uuid PRIMARY KEY,agent text NOT NULL,action text NOT NULL,entity_id uuid,status text NOT NULL,detail jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_activity(agent text PRIMARY KEY,state text NOT NULL,task text NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_log_time ON audit_log(created_at DESC,id DESC);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS access_confirmed boolean NOT NULL DEFAULT false;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS workspace_mode text NOT NULL DEFAULT 'prepare' CHECK(workspace_mode IN ('prepare','outreach'));
CREATE TABLE IF NOT EXISTS profile_imports(id uuid PRIMARY KEY,source_hash text UNIQUE NOT NULL,raw_text text NOT NULL,preview jsonb NOT NULL,status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS knowledge_documents(id uuid PRIMARY KEY,title text NOT NULL,content text NOT NULL,content_hash text UNIQUE NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS custom_skills(id uuid PRIMARY KEY,name text NOT NULL,instructions text NOT NULL,enabled boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS work_items(id uuid PRIMARY KEY,opportunity_id uuid REFERENCES opportunities(id),kind text NOT NULL CHECK(kind IN ('email','followup','meeting')),recipient text NOT NULL,title text NOT NULL,body text NOT NULL DEFAULT '',due_at timestamptz,minutes integer NOT NULL DEFAULT 30,status text NOT NULL DEFAULT 'draft',approval_hash text,provider_id text,error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS one_work_payload ON work_items(kind,recipient,md5(length(title)::text||':'||title||body),COALESCE(due_at,'epoch'::timestamptz));
CREATE TABLE IF NOT EXISTS suppressed_contacts(email text PRIMARY KEY,reason text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());

ALTER TABLE work_items ADD COLUMN IF NOT EXISTS approved_account_id text;

ALTER TABLE runs ADD COLUMN IF NOT EXISTS model_id text;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS auth_mode text;
ALTER TABLE runs ADD COLUMN IF NOT EXISTS cached_input_tokens integer;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS batch_minutes integer NOT NULL DEFAULT 60 CHECK(batch_minutes IN (60,180,360,720,1440));
ALTER TABLE settings ADD COLUMN IF NOT EXISTS next_batch_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE settings ADD COLUMN IF NOT EXISTS client_prospecting boolean NOT NULL DEFAULT true;
CREATE TABLE IF NOT EXISTS outreach_batches(id uuid PRIMARY KEY,status text NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz,sources_checked integer NOT NULL DEFAULT 0,leads_added integer NOT NULL DEFAULT 0,packages_queued integer NOT NULL DEFAULT 0,drafts_created integer NOT NULL DEFAULT 0,errors jsonb NOT NULL DEFAULT '[]');
ALTER TABLE work_items ADD COLUMN IF NOT EXISTS auto_generated boolean NOT NULL DEFAULT false;
ALTER TABLE work_items ADD COLUMN IF NOT EXISTS draft_edited boolean NOT NULL DEFAULT false;
ALTER TABLE work_items ADD COLUMN IF NOT EXISTS auto_source_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS one_auto_outreach_draft ON work_items(opportunity_id) WHERE auto_generated;
